import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';

const root=path.dirname(new URL(import.meta.url).pathname).replace(/^\//,'');
const parse=p=>Object.fromEntries(fs.readFileSync(p,'utf8').split(/\r?\n/).flatMap(line=>{const i=line.indexOf('=');return i>0&&!line.trim().startsWith('#')?[[line.slice(0,i).trim(),line.slice(i+1).trim()]]:[]}));
const env=parse('C:/Documents2/global.env');
const page=fs.readFileSync(path.join(root,'index.html'));
const host=fs.readFileSync(path.join(root,'host.png'));
const localUrl=env.OLLAMA_URL||'http://127.0.0.1:11434';
const localModel=env.OLLAMA_MODEL||'qwen3:4b';
const projects={"3000studios.vip":"C:/Users/MrJws/OneDrive/Workspaces/3000studios.vip","boughtitonline.com":"C:/Users/MrJws/OneDrive/Workspaces/boughtitonline.com","campdream.store":"C:/Users/MrJws/OneDrive/Workspaces/campdream.store","findmerates.com":"C:/Users/MrJws/OneDrive/Workspaces/findmerates.com","fuckyou.site":"C:/Users/MrJws/OneDrive/Workspaces/fuckyou.site","getnexa.space":"C:/Users/MrJws/OneDrive/Workspaces/getnexa.space","myappai.net":"C:/Users/MrJws/OneDrive/Workspaces/myappai.net","myappai.org":"C:/Users/MrJws/OneDrive/Workspaces/myappai.org","paigeswain.com":"C:/Users/MrJws/OneDrive/Workspaces/paigeswain.com","playstorewizard.pro":"C:/Users/MrJws/OneDrive/Workspaces/playstorewizard.pro","pondco.online":"C:/Users/MrJws/OneDrive/Workspaces/pondco.online","referrals.live":"C:/Users/MrJws/OneDrive/Workspaces/referrals.live","swain.pro":"C:/Users/MrJws/OneDrive/Workspaces/swain.pro","theunitedstates.site":"C:/Users/MrJws/OneDrive/Workspaces/theunitedstates.site","voicetowebsite.com":"C:/Users/MrJws/OneDrive/Workspaces/voicetowebsite-copyright-mrjwswain","calistique.xyz":null,"campdreamga.com":null,"thecajunmenu.site":null,"tmack48.com":null,"voicetowebsite.xyz":null};
const jobs=new Map();
const briefPolicy=`You are Nova, 3000Studios' operations chief. Be decisive and concise: give the chosen worker, project, terminal command or action it will run, and the required verification. Treat ordinary scoped code editing, tests, verified project dependency installs, file creation, git commits, pushes to main, and deployment verification as authorized by the user's mission; do not give a step-by-step tutorial or ask routine permission questions. Choose one worker: Codex for complex verified implementation, OpenCode for fast local coding, Grok for independent code tasks. The word BAZINGA is an owner-intent marker: acknowledge it as authorization for the scoped mission and log it, but it never overrides safety, account protections, billing, credential handling, legal obligations, or the truthful live-status rule. Never perform money, deletion, publishing, checkout, secret, customer-data, billing, domain, or credential actions without explicit approval. HARD TRUTH POLICY: never claim anything is live, deployed, published, working, or verified unless personally visually checked on the production site/store after deployment. A commit, build, push, or deployment log is not proof. State visual evidence or say verification is pending. Be sharp, human, slightly funny, never abusive.`;
const secure=res=>{res.setHeader('x-content-type-options','nosniff');res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','no-referrer');res.setHeader('permissions-policy','camera=(), geolocation=(), payment=(), usb=()');res.setHeader('content-security-policy',"default-src 'self'; connect-src 'self'; img-src 'self'; media-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'");};
const send=(res,status,body)=>{secure(res);res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body));};
const textFrom=j=>j.output_text||j.output?.flatMap(i=>i.content||[]).filter(p=>p.type==='output_text').map(p=>p.text).join('')||j.error?.message||'No response';
async function ollamaReady(){try{const r=await fetch(`${localUrl}/api/tags`,{signal:AbortSignal.timeout(900)});return r.ok}catch{return false}}
async function localBrief(task){const r=await fetch(`${localUrl}/api/chat`,{method:'POST',headers:{'content-type':'application/json'},signal:AbortSignal.timeout(8000),body:JSON.stringify({model:localModel,stream:false,think:false,keep_alive:'10m',options:{temperature:.35,num_predict:300},messages:[{role:'system',content:briefPolicy},{role:'user',content:`Task: ${task}`}]})});const j=await r.json();if(!r.ok||!j.message?.content)throw Error('Local model unavailable');return j.message.content}
async function cloudBrief(task){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-4.1-mini',input:`${briefPolicy}\nTask: ${task}`})});const j=await r.json();if(!r.ok)throw Error(textFrom(j));return textFrom(j)}
function startJob({project,agent,task}){const cwd=projects[project];if(!cwd)throw Error(`${project} has no mapped canonical source workspace.`);const id=`job-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;const job={id,project,agent,status:'running',startedAt:new Date().toISOString(),output:[],command:''};const instructions=`${task}\n\nYou own this mission end-to-end. Inspect the project instructions, implement the scoped work, run relevant checks, commit and push main when appropriate, then visually verify the real production site/store. Never claim live without visual evidence. Report exact errors if blocked. Do not ask for a routine confirmation.`;const cmd=agent==='Grok'?'grok':'opencode';const args=agent==='Grok'?['--cwd',cwd,'--permission-mode','acceptEdits',instructions]:['run','--agent','build',instructions];job.command=`${cmd} ${args.map(x=>JSON.stringify(x)).join(' ')}`;jobs.set(id,job);const child=spawn(cmd,args,{cwd,windowsHide:true});const append=(label,data)=>{const text=String(data).trim();if(text)job.output.push(`[${label}] ${text}`);if(job.output.length>80)job.output.splice(0,job.output.length-80)};child.stdout.on('data',d=>append('out',d));child.stderr.on('data',d=>append('err',d));child.on('error',e=>{append('error',e.message);job.status='failed';job.finishedAt=new Date().toISOString()});child.on('close',code=>{job.exitCode=code;job.status=code===0?'completed':'failed';job.finishedAt=new Date().toISOString();append('system',code===0?'Worker finished. Production verification must be read from its final report.':`Worker exited with code ${code}.`)});return job}
http.createServer(async(req,res)=>{
  if(req.method==='GET'&&req.url==='/'){secure(res);res.writeHead(200,{'content-type':'text/html','cache-control':'no-store'});return res.end(page)}
  if(req.method==='GET'&&req.url==='/host.png'){secure(res);res.writeHead(200,{'content-type':'image/png','cache-control':'no-store'});return res.end(host)}
  if(req.method==='GET'&&req.url==='/manifest.webmanifest'){secure(res);res.writeHead(200,{'content-type':'application/manifest+json','cache-control':'no-store'});return res.end(fs.readFileSync(path.join(root,'manifest.webmanifest')))}
  if(req.method==='GET'&&req.url==='/sw.js'){secure(res);res.writeHead(200,{'content-type':'application/javascript','cache-control':'no-store'});return res.end(fs.readFileSync(path.join(root,'sw.js')))}
  if(req.method==='GET'&&req.url==='/client-enhancements.js'){secure(res);res.writeHead(200,{'content-type':'application/javascript','cache-control':'no-store'});return res.end(fs.readFileSync(path.join(root,'client-enhancements.js')))}
  if(req.method==='GET'&&req.url==='/health')return send(res,200,{ok:true,local:{available:await ollamaReady(),model:localModel},cloud:{available:Boolean(env.OPENAI_API_KEY)},voice:{available:Boolean(env.OPENAI_API_KEY)}});
  if(Number(req.headers['content-length']||0)>65536)return send(res,413,{error:'Request is too large.'});
  let body='';for await(const chunk of req){body+=chunk;if(body.length>65536)return send(res,413,{error:'Request is too large.'})}let q={};try{q=JSON.parse(body||'{}')}catch{}
  if(req.url==='/projects')return send(res,200,{projects:Object.keys(projects)});
  if(req.method==='GET'&&req.url.startsWith('/jobs/')){const job=jobs.get(req.url.slice('/jobs/'.length));return job?send(res,200,job):send(res,404,{error:'Job not found.'})}
  if(req.url==='/mission'){try{const task=String(q.task||'').slice(0,6000),agent=q.agent==='Grok'?'Grok':'OpenCode';if(!task)return send(res,400,{error:'Tell Nova what needs doing.'});const job=startJob({project:q.project,agent,task});return send(res,202,{job:{id:job.id,status:job.status,command:job.command}})}catch(e){return send(res,409,{error:e.message})}}
  if(req.url==='/chat'){
    const task=String(q.message||'').slice(0,6000);if(!task)return send(res,400,{error:'Tell Nova what you need done.'});
    try{let text,provider='openai';if(q.mode!=='cloud'&&await ollamaReady()){try{text=await localBrief(task);provider='ollama'}catch{}}if(!text)text=await cloudBrief(task);return send(res,200,{text,provider})}catch{return send(res,502,{error:'Nova could not reach a configured model. Check the local service or OpenAI balance.'})}
  }
  if(req.url==='/voice'){
    const input=String(q.text||'').slice(0,1800);if(!input)return send(res,400,{error:'Nothing to speak.'});
    try{const r=await fetch('https://api.openai.com/v1/audio/speech',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',voice:env.OPENAI_TTS_VOICE||'marin',input,format:'mp3'})});if(!r.ok)return send(res,502,{error:'Natural voice is unavailable.'});res.writeHead(200,{'content-type':'audio/mpeg','cache-control':'no-store'});return res.end(Buffer.from(await r.arrayBuffer()))}catch{return send(res,502,{error:'Natural voice is unavailable.'})}
  }
  if(req.url==='/launch'){
    const cwd=projects[q.project],agent=q.agent==='Grok'?'Grok':q.agent==='OpenCode'?'OpenCode':null;if(!agent||!(q.project in projects))return send(res,400,{error:'Choose a known project and worker.'});if(!cwd)return send(res,409,{error:`${q.project} is listed, but its canonical source workspace has not been mapped yet. No worker was opened.`});const cmd=agent==='Grok'?'grok':'opencode';const args=agent==='Grok'?['--cwd',cwd,'--permission-mode','acceptEdits',String(q.task||'')]:['run','--agent','build',String(q.task||'')];const visibleCommand=`Set-Location '${cwd}'; ${cmd} ${args.map(x=>`'${x.replaceAll("'","''")}'`).join(' ')}`;spawn('powershell.exe',['-NoExit','-Command',visibleCommand],{detached:true,stdio:'ignore'}).unref();return send(res,200,{text:`Opened ${agent} in ${q.project}. It must commit and push main, then visually verify production before reporting anything live.`,command:visibleCommand});
  }
  return send(res,404,{error:'not found'});
}).listen(3410,'127.0.0.1',()=>console.log(`Orchestrator: http://127.0.0.1:3410 | local model: ${localModel}`));
